id: P3AF0F777
initial_creation_type: ocr
source_metadata:
  volumes:
    54defd7ce79f4465b54cfa5da72eef5c:
      base_file: v005.txt
      image_group_id: I1PD95850
      title: གཏོར་མའི་ཆོ་ག།
      total_pages: 2069
      volume_number: 5
